name: PR test and preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  PRODUCTION: false

on: 
  pull_request

jobs:
  contracts_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Install Aptos Tooling
        working-directory: ./.github/utilities
        run: chmod u+x dev_setup.sh; ./dev_setup.sh -v

      - name: Installing Dependencies
        working-directory: ./contracts/aptos
        run: yarn

      - name: Run tests
        working-directory: ./contracts/aptos
        run: yarn test:integration
      
  vercel_preview_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Installing Dependencies
        working-directory: ./web
        run: yarn

      - name: Deploy All to Vercel
        working-directory: ./web
        run: yarn build_vercel